name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-glightbox
          pip install pymdown-extensions
          pip install pygments
          pip install mkdocs-static-i18n
          pip install mkdocs-codeinclude-plugin
          pip install mkdocs-video
          pip install mkdocs-glightbox
          pip install mdx_truly_sane_lists
          pip install mkdocs-blueprintue
      - name: Deploy docs
        run: mkdocs gh-deploy --force
