name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy docs
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-glightbox
      - run: pip install pymdown-extensions
      - run: pip install pygments
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-codeinclude-plugin
      - run: pip install mkdocs-video
      - run: mkdocs gh-deploy --force
          